; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lora_e5_dev_board]
platform = ststm32
board = lora_e5_dev_board
framework = arduino

board_build.mcu = stm32wle5jc

; change MCU frequency
board_build.f_cpu = 48000000L

upload_protocol = stlink
debug_tool = stlink

debug_build_flags = -O0 -ggdb3 -g3

lib_deps =
    adafruit/Adafruit BME280 Library
    stm32duino/STM32duino Low Power
    jgromes/RadioLib