M48
; DRILL file {KiCad 6.0.7+dfsg-1build1} date Do 23 Feb 2023 20:10:11 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-23T20:10:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1build1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X2.874Y-1.2598
X2.874Y-3.622
X6.063Y-1.2598
X6.063Y-3.622
T0
M30
