M48
; DRILL file {KiCad 9.0.1} date 2025-04-07T12:08:39+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-07T12:08:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X2.8419Y-3.0094
X6.7274Y-2.8811
T2
X4.7016Y-1.8632
X5.6179Y-2.8061
M30
