M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Do 16 Mär 2023 17:45:10 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-16T17:45:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.335Y-3.1795
X4.5626Y-3.1795
T2
X3.935Y-0.8809
X4.9902Y-3.1506
X6.8386Y-1.9961
T3
X3.7618Y-3.3878
X6.8917Y-3.4429
X6.8937Y-0.7087
T0
M30
